import { Types } from "mongoose";
import { AuthenticatedUserContext, IPermissionGrant } from "@/types/rbac";

/**
 * Record boundary checks for controllers that load a single document by id and
 * then compare its branch in JavaScript.
 *
 * Prefer pushing `auth.filter` into the repository query: those filters are
 * generated by `ScopeResolver` and are applied by MongoDB, so a record that
 * carries no branch cannot match a branch filter at all. This helper exists for
 * the handlers that already hold the loaded document.
 *
 * The rule here is deliberately *fail closed*. The inline pattern it replaces
 * was written as
 *
 *     if (record.branchId && record.branchId !== context.branchId) deny;
 *
 * which grants access to every record whose branch is null or unset - an
 * unassigned invoice, admission or prescription would have been readable and
 * editable from any branch.
 */
export interface BoundaryCheck {
  allowed: boolean;
  statusCode: number;
  message: string;
}

/** Field names that can hold a record's owning branch, most specific first. */
const BRANCH_FIELDS = ["branchId", "organizationId"] as const;

function toIdString(value: unknown): string | null {
  if (!value) return null;
  if (value instanceof Types.ObjectId) return value.toString();
  if (typeof value === "string") return value;
  if (typeof value === "object" && value !== null) {
    const nested = value as { _id?: unknown };
    if (nested._id) return toIdString(nested._id);
  }
  return null;
}

/** The branch that owns `record`, or null when it has none recorded. */
export function recordBranchId(record: unknown): string | null {
  if (!record || typeof record !== "object") return null;

  for (const field of BRANCH_FIELDS) {
    const value = (record as Record<string, unknown>)[field];
    const id = toIdString(value);
    if (id) return id;
  }

  return null;
}

/**
 * Confirms `record` sits inside the boundary implied by the caller's grant.
 *
 * Returns an allowed result when the grant is global, when the actor has no
 * branch/organization context to compare against, or when the record's branch
 * matches. Everything else is denied, including a record with no branch set.
 */
export function checkRecordBoundary(
  record: unknown,
  context: Pick<AuthenticatedUserContext, "branchId" | "organizationId">,
  grant: Pick<IPermissionGrant, "orgScope">
): BoundaryCheck {
  if (grant.orgScope === "GLOBAL") return { allowed: true, statusCode: 200, message: "" };

  const actorBoundary = toIdString(context.branchId) ?? toIdString(context.organizationId);

  // No boundary to enforce against: the actor is unscoped by configuration, so
  // there is nothing to compare and no record can be outside it.
  if (!actorBoundary) return { allowed: true, statusCode: 200, message: "" };

  const recordBoundary = recordBranchId(record);

  if (!recordBoundary) {
    return {
      allowed: false,
      statusCode: 403,
      message: "Forbidden: record has no branch assigned and cannot be scoped to your access"
    };
  }

  if (recordBoundary !== actorBoundary) {
    return {
      allowed: false,
      statusCode: 403,
      message: "Forbidden: record belongs to another branch"
    };
  }

  return { allowed: true, statusCode: 200, message: "" };
}